# Generated by Django 4.0.3 on 2022-12-27 08:08

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('image', models.ImageField(upload_to=store.models.get_file_path)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Meta Title')),
                ('meta_keyword', models.CharField(max_length=250, verbose_name='Meta Keyword')),
                ('meta_description', models.CharField(max_length=550, verbose_name='Meta Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('product_image', models.ImageField(upload_to=store.models.get_file_path)),
                ('short_description', models.TextField(max_length=200, verbose_name='Description')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('orginal_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=100, verbose_name='Meta Title')),
                ('meta_keyword', models.CharField(max_length=250, verbose_name='Meta Keyword')),
                ('meta_description', models.CharField(max_length=550, verbose_name='Meta Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
