# Generated by Django 4.0.3 on 2022-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Short Description'),
        ),
    ]
