# Generated by Django 4.0.3 on 2022-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_ingridient_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingridient',
            field=models.TextField(default='Not Availabel', max_length=500, verbose_name='Ingridient'),
        ),
    ]
