# Generated by Django 4.0.3 on 2023-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(default='Not Availabel', max_length=600, verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='whyuseinstapeel',
            field=models.TextField(default='Not Availabel', max_length=600, verbose_name='Why Use Instapeel'),
        ),
    ]
