# Generated by Django 4.0.3 on 2023-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_benefits_product_whyuseinstapeel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='howtouse',
            field=models.TextField(default='Not Availabel', max_length=600, verbose_name='How to Use'),
        ),
    ]
