# Generated by Django 4.0.3 on 2023-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/products/%Y/%m/%d'),
        ),
    ]
