# Generated by Django 4.0.3 on 2023-02-01 13:10

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productmultiimage',
            field=models.ImageField(default=None, upload_to=store.models.get_file_path_for_multi),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
