# Generated by Django 4.0.3 on 2023-02-02 05:52

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_productmultiimage_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productmultiimage',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to=store.models.get_file_path_for_multi, verbose_name='Image')),
                ('prod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
