# Generated by Django 4.0.3 on 2023-02-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='imag',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='prod',
            new_name='product',
        ),
    ]
